# travis continuous integration declaration for
# Emuflight

env:
  matrix:
    - GOAL=targets-group-1 # make all (in parallel)
    - GOAL=targets-group-2
    - GOAL=targets-group-rest
    # - GOAL=FURYF4OSD
    # - GOAL=MATEKF411
  global:
    # - DEBUG=RELWITHDEBINFO # debug symbols
    - CCACHE_SLOPPINESS="file_macro,time_macros,include_file_mtime,include_file_ctime,file_stat_matches"
    - MAKEFLAGS="-j 2" # each travis vm has 2 cpu cores
    - PATH="$HOME/.local/bin:$PATH" # "user" installs (pip and stuff)
git:
  depth: 5 # quick clone
  quiet: true # save on logfiles

addons:
  apt:
    packages:
      - build-essential
      - ccache
      - clang
      - g++
      - git
      - libblocksruntime-dev # required for linking on tests - http://mackyle.github.io/blocksruntime/
      - libc6-i386
      - llvm
      - time

cache:
  ccache: true
  pip: true
  directories:
  - downloads
  - tools

dist: bionic # ubuntu
language: cpp
compiler: clang

before_install:
  - pip install --user --upgrade j2cli

script:
  - ./.travis.sh # main
  - ccache --show-stats

deploy:
  - provider: releases
    skip_cleanup: true # do not delete what has just been built
    name: "${TRAVIS_TAG}"
    tag_name: "${TRAVIS_TAG}"
    target_commitish: "${TRAVIS_COMMIT}"
    file: obj/*.hex
    draft: true
    prerelease: true
    overwrite: true
    token: "${GITHUB_TOKEN}"
    on:
      tags: true
  - provider: bintray
    file: bintray-conf.json
    user: "${BINTRAY_USER}"
    key: "${BINTRAY_API_KEY}"
    skip_cleanup: true # do not delete what has just been built
    on:
      tags: true
  
after_deploy:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
